services:
  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim:latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalogdb:
    image: postgres

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile

  catalog-api-dapr:
    image: "daprio/daprd:1.13.5"
    network_mode: "service:catalog-api"
    depends_on:
      - catalog-api

  basket-api:
    image: ${DOCKER_REGISTRY-}basket-api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.Api/Dockerfile
    depends_on:
      - redis
      - rabbitmq

  basket-api-dapr:
    image: "daprio/daprd:1.13.5"
    network_mode: "service:basket-api"
    depends_on:
      - basket-api

  dapr-placement:
    image: "daprio/dapr:1.13.5"

volumes:
  postgres-catalog:
