services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim:latest

  seq:
    image: datalust/seq:latest

  catalogdb:
    image: postgres

  basket-api:
    image: ${DOCKER_REGISTRY-racketsport/}basket.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.Api/Dockerfile
    depends_on:
      - redis

  basket-api-dapr:
    image: "daprio/daprd:1.13.5"
    network_mode: "service:basket-api"
    depends_on:
      - basket-api

  catalog-api:
    image: ${DOCKER_REGISTRY-racketsport/}catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile
    depends_on:
      - catalogdb

  catalog-api-dapr:
    image: "daprio/daprd:1.13.5"
    network_mode: "service:catalog-api"
    depends_on:
      - catalog-api

  dapr-placement:
    image: "daprio/dapr:1.13.5"
